import { defineConfig } from 'vite'
// ...existing code...

export default defineConfig({
  // ...existing code...
  base: process.env.NODE_ENV === 'production' ? '/ccdi-ods-ui/' : '/',
  // ...existing code...
})